import React, { useState, useRef, useEffect } from 'react';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { PageProps } from '@/types';
import { Shield, KeyRound, ArrowLeft, Loader2, AlertCircle, Copy, Check, QrCode } from 'lucide-react';

interface MfaChallengeProps {
    requires_setup: boolean;
    qr_code_svg?: string | null;
    manual_key?: string | null;
}

export default function MfaChallenge({
    requires_setup,
    qr_code_svg,
    manual_key,
}: MfaChallengeProps) {
    const { appName, identity } = usePage<PageProps>().props;
    const displayName = identity?.name || appName || 'Wholesale Distribution Management System';

    const [useRecoveryCode, setUseRecoveryCode] = useState(false);
    const [copiedKey, setCopiedKey] = useState(false);
    const codeInputRef = useRef<HTMLInputElement>(null);

    const { data, setData, post, processing, errors, reset } = useForm({
        code: '',
        recovery_code: '',
    });

    useEffect(() => {
        codeInputRef.current?.focus();
    }, [useRecoveryCode]);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        post('/login/mfa', {
            onFinish: () => reset('code', 'recovery_code'),
        });
    };

    const handleCopyKey = () => {
        if (manual_key) {
            navigator.clipboard.writeText(manual_key.replace(/\s+/g, ''));
            setCopiedKey(true);
            setTimeout(() => setCopiedKey(false), 2000);
        }
    };

    const toggleMode = () => {
        setUseRecoveryCode(!useRecoveryCode);
        setData({
            code: '',
            recovery_code: '',
        });
    };

    return (
        <div className="min-h-screen bg-slate-950 text-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
            <Head title={`Two-Factor Authentication — ${displayName}`} />

            <div className="sm:mx-auto sm:w-full sm:max-w-md">
                <div className="flex justify-center">
                    <div className="w-12 h-12 rounded-xl bg-indigo-600/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shadow-inner">
                        <Shield className="w-6 h-6" aria-hidden="true" />
                    </div>
                </div>
                <h1 className="mt-4 text-center text-2xl font-bold tracking-tight text-white">
                    {requires_setup ? 'Set Up Two-Factor Authentication' : 'Two-Factor Authentication'}
                </h1>
                <p className="mt-2 text-center text-sm text-slate-400">
                    {requires_setup
                        ? 'Multi-factor authentication is required for your role. Configure an authenticator application to proceed.'
                        : useRecoveryCode
                        ? 'Enter one of your emergency recovery codes to authenticate.'
                        : 'Enter the 6-digit security code generated by your authenticator app.'}
                </p>
            </div>

            <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md px-4 sm:px-0">
                <div className="bg-slate-900/60 border border-slate-800/80 backdrop-blur-xl py-8 px-6 sm:px-10 rounded-2xl shadow-2xl">
                    {/* Setup QR section if required */}
                    {requires_setup && qr_code_svg && (
                        <div className="mb-6 p-4 rounded-xl bg-slate-950/80 border border-slate-800 flex flex-col items-center">
                            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-indigo-400 mb-3">
                                <QrCode className="w-4 h-4" />
                                <span>Scan with Authenticator App</span>
                            </div>
                            <div
                                className="bg-white p-3 rounded-lg shadow-md"
                                dangerouslySetInnerHTML={{ __html: qr_code_svg }}
                                aria-label="Authenticator setup QR code"
                            />

                            {manual_key && (
                                <div className="mt-4 w-full text-center">
                                    <span className="text-xs text-slate-400 block mb-1">
                                        Cannot scan? Enter manual key:
                                    </span>
                                    <div className="flex items-center justify-center gap-2 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-lg text-xs font-mono text-slate-200">
                                        <span>{manual_key}</span>
                                        <button
                                            type="button"
                                            onClick={handleCopyKey}
                                            className="text-slate-400 hover:text-white transition-colors"
                                            title="Copy manual key"
                                            aria-label="Copy manual key"
                                        >
                                            {copiedKey ? (
                                                <Check className="w-3.5 h-3.5 text-emerald-400" />
                                            ) : (
                                                <Copy className="w-3.5 h-3.5" />
                                            )}
                                        </button>
                                    </div>
                                </div>
                            )}
                        </div>
                    )}

                    {/* Generic error alerts */}
                    {(errors.code || errors.recovery_code) && (
                        <div
                            role="alert"
                            className="mb-6 p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-300 text-sm flex items-start gap-2.5"
                        >
                            <AlertCircle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" aria-hidden="true" />
                            <div>{errors.code || errors.recovery_code}</div>
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="space-y-6">
                        {!useRecoveryCode ? (
                            <div>
                                <label
                                    htmlFor="code"
                                    className="block text-sm font-medium text-slate-200 mb-1.5"
                                >
                                    Authentication Code
                                </label>
                                <Input
                                    id="code"
                                    ref={codeInputRef}
                                    type="text"
                                    inputMode="numeric"
                                    pattern="[0-9]*"
                                    maxLength={6}
                                    autoComplete="one-time-code"
                                    placeholder="123456"
                                    value={data.code}
                                    onChange={(e) => setData('code', e.target.value.replace(/[^0-9]/g, ''))}
                                    className="text-center font-mono text-xl tracking-widest h-12 bg-slate-950/60 border-slate-700 text-white placeholder:text-slate-600 focus:border-indigo-500 focus:ring-indigo-500"
                                    required
                                />
                            </div>
                        ) : (
                            <div>
                                <label
                                    htmlFor="recovery_code"
                                    className="block text-sm font-medium text-slate-200 mb-1.5"
                                >
                                    Recovery Code
                                </label>
                                <Input
                                    id="recovery_code"
                                    ref={codeInputRef}
                                    type="text"
                                    autoComplete="off"
                                    placeholder="XXXXX-XXXXX"
                                    value={data.recovery_code}
                                    onChange={(e) => setData('recovery_code', e.target.value)}
                                    className="text-center font-mono text-base tracking-wider h-12 bg-slate-950/60 border-slate-700 text-white placeholder:text-slate-600 focus:border-indigo-500 focus:ring-indigo-500 uppercase"
                                    required
                                />
                            </div>
                        )}

                        <Button
                            type="submit"
                            disabled={processing}
                            className="w-full h-11 bg-indigo-600 hover:bg-indigo-500 text-white font-medium shadow-md transition-all flex items-center justify-center gap-2"
                        >
                            {processing ? (
                                <>
                                    <Loader2 className="w-4 h-4 animate-spin" aria-hidden="true" />
                                    <span>Verifying...</span>
                                </>
                            ) : (
                                <span>{requires_setup ? 'Complete Enrollment' : 'Verify & Continue'}</span>
                            )}
                        </Button>
                    </form>

                    {!requires_setup && (
                        <div className="mt-6 pt-5 border-t border-slate-800 text-center">
                            <button
                                type="button"
                                onClick={toggleMode}
                                className="text-xs text-indigo-400 hover:text-indigo-300 font-medium inline-flex items-center gap-1.5 transition-colors cursor-pointer py-1"
                            >
                                <KeyRound className="w-3.5 h-3.5" />
                                <span>
                                    {useRecoveryCode
                                        ? 'Use an authenticator app code instead'
                                        : 'Use an emergency recovery code'}
                                </span>
                            </button>
                        </div>
                    )}

                    <div className="mt-4 text-center">
                        <Link
                            href="/login"
                            className="text-xs text-slate-400 hover:text-slate-200 inline-flex items-center gap-1 transition-colors"
                        >
                            <ArrowLeft className="w-3.5 h-3.5" />
                            <span>Back to login</span>
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
